### ISSUE TITLE
Failure to run `csa-ccm` gem

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/csa-caiq#5]
See https://travis-ci.com/metanorma/csa-caiq/builds/110355941

```
bundle exec csa-ccm ccm-yaml 3.0.1 -o caiq.yaml
/home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/central_directory.rb:143:in `get_e_o_c_d': XLSX file format error: Zip end of central directory signature not found (Zip::Error)
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/central_directory.rb:103:in `read_e_o_c_d'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/central_directory.rb:136:in `read_from_stream'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/file.rb:76:in `block in initialize'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/file.rb:75:in `open'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/file.rb:75:in `initialize'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/file.rb:97:in `new'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyzip-1.2.2/lib/zip/file.rb:97:in `open'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/rubyXL-3.4.3/lib/rubyXL/parser.rb:7:in `parse'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/csa-ccm-0.1.2/lib/csa/ccm/matrix.rb:20:in `initialize'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/csa-ccm-0.1.2/lib/csa/ccm/matrix.rb:99:in `new'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/csa-ccm-0.1.2/lib/csa/ccm/matrix.rb:99:in `from_xlsx'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/csa-ccm-0.1.2/lib/csa/ccm/cli/command.rb:29:in `ccm_yaml'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/command.rb:27:in `run'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/invocation.rb:126:in `invoke_command'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor.rb:387:in `dispatch'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/thor-0.20.3/lib/thor/base.rb:466:in `start'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/csa-ccm-0.1.2/exe/csa-ccm:7:in `<top (required)>'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/bin/csa-ccm:23:in `load'
	from /home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/bin/csa-ccm:23:in `<main>'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `eval'
	from /home/travis/.rvm/gems/ruby-2.5.3/bin/ruby_executable_hooks:24:in `<main>'
Makefile:128: recipe for target 'caiq.yaml' failed
make: *** [caiq.yaml] Error 1
```

**Comment by ronaldtse** [comment]
Maybe this is due to running on Travis Xenial rather than Trusty. Trying Trusty now.

**Comment by CAMOBAP** [comment]
Works locally on OSX I have found this https://github.com/rubyzip/rubyzip/issues/288 but the investigation still in progress

**Comment by ronaldtse** [comment]
Looks like this problem is fixed?
