### ISSUE TITLE
Missing puppeteer in Trusty

### ISSUE THREAD

**Issue by ronaldtse** [metanorma/csa-caiq#7]
The Trusty build (14.04) is marked "passed" but is actually missing proper install of `puppeteer`. This is an issue with https://github.com/metanorma/metanorma-linux-setup/pull/7 .

https://travis-ci.com/metanorma/csa-caiq/builds/110664505?utm_medium=notification&utm_source=email

```
module.js:538
    throw err;
    ^
Error: Cannot find module 'puppeteer'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/travis/build/metanorma/csa-caiq/vendor/bundle/ruby/2.5.0/gems/metanorma-0.3.11/bin/metanorma-pdf.js:4:19)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
mkdir -p published  && \
	cp -a document.* published/ && \
	cp document.html published/index.html; \
	if [ -d "images" ]; then cp -a images published; fi
The command "make clean all publish" exited with 0.
```

**Comment by ronaldtse** [comment]
This needs to be fixed. Once it is fixed, please revert 1c49905 (which disables PDF output). Thanks!
